name: Push Docker Image

on:
  push:
    tags: 
      - morph-v*
    branches:
      - main
      - release/*

env:
  IMAGE_NAME: go-ethereum

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure the full history is fetched so tags are available
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t "${IMAGE_NAME}"